# https://rubocop.readthedocs.io/en/latest/

inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/SpaceAfterNot:
  Enabled: false

Layout/TrailingBlankLines:
  EnforcedStyle: final_blank_line

Lint/UnusedBlockArgument:
  Enabled: false

