inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'config/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
