# THIS FILE LEFT BLANK
# - consolidate all settings into config/settings/{stage}.yml
# - the  config/settings/test.yml can serve as a useful template
# - arbitrary settings file can be assigned to CLUSTER_SETTINGS, e.g.
# export CLUSTER_SETTINGS=~/my_cluster/settings.yml
#
