# http://docs.aws.amazon.com/sdk-for-ruby/v2/developer-guide/setup-config.html

# Some image-ids as of 2017-08
# Amazon Linux AMI 2017.03.1 (HVM), SSD Volume Type - ami-aa5ebdd2
# Red Hat Enterprise Linux 7.4 (HVM), SSD Volume Type - ami-9fa343e7
# Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-6e1a0117

aws:
  # when access_key_id and secret_access_key are blank, Settings will try to use ENV values
  access_key_id:
  secret_access_key:
  region: us-west-2
  availability_zones:
    - us-west-2a
    - us-west-2b
    - us-west-2c

  # ---
  # EC2 Instance Params
  # - each instance block begins with a 'key' to identify the instance
  # - use the same 'key' value to name the instance and put it in the 'tag_name' value
  # - use '_' in all 'key' and tag values, not '-' (because Settings.aws.keys uses symbols)

  instance_default: &default
    region: us-west-2
    image_id: ami-6e1a0117  # Ubuntu
    distrib_id: Ubuntu
    min_count: 1
    max_count: 1
    instance_type: t2.micro
    availability_zone: us-west-2a
    key_name: test-dlweber
    tag_name: instance_default
    tag_group: dev_nodes
    tag_manager: dlweber
    tag_service:
    tag_stage: development

  instance_test:
    <<: *default
    instance_type: t2.micro
    tag_name: instance_test
    tag_stage: test

