# These settings are merged into config/settings.yml

# - these development settings may not be fault tolerant
# - these settings consolidate services on single nodes that should be replicated
#   on multiple nodes in different availability zones for production fault tolerance

aws:

  instance_default_dev: &DevDefault
    region: us-west-2
    image_id: ami-6e1a0117  # Ubuntu
    distrib_id: Ubuntu
    user: ubuntu
    min_count: 1
    max_count: 1
    instance_type: t2.2xlarge
    availability_zone: us-west-2a
    key_name: dlweber-dev   # TODO: replace this key pair
    tag_name: dev_default
    tag_group: dev_nodes
    tag_manager: dlweber
    tag_service:
    tag_stage: development

  # ---
  # Zookeeper Nodes
  # - note definition and use of defaults: ZookeeperDefaults
  # - it's important that each instance has 'zookeeper' in the key and tag_name (case sensitive)

  dev_zookeeper1: &ZookeeperDefaults
    <<: *DevDefault
    instance_type: t2.medium
    tag_service: zookeeper
    tag_group: dev_zookeeper
    tag_name: dev_zookeeper1
    availability_zone: us-west-2a  # need one node in each zone

  dev_zookeeper2:
    <<: *ZookeeperDefaults
    tag_name: dev_zookeeper2
    availability_zone: us-west-2b  # need one node in each zone

  dev_zookeeper3:
    <<: *ZookeeperDefaults
    tag_name: dev_zookeeper3
    availability_zone: us-west-2c  # need one node in each zone

  # ---
  # Mesos Nodes
  # - note definition and use of defaults: MesosMasterDefaults, MesosAgentDefaults
  # - note definition and use of defaults: MesosMasterDefaults, MesosAgentDefaults
  # - it's important that each instance has 'mesos' in the key and tag_name (case sensitive)

  dev_mesos_master: &MesosMasterDefaults
    <<: *DevDefault
    tag_service: mesos
    tag_group: dev_mesos_master
    tag_name: dev_mesos_master1
    availability_zone: us-west-2a  # need one node in each zone

  dev_mesos_agent1: &MesosAgentDefaults
    <<: *DevDefault
    instance_type: c4.4xlarge
    tag_service: mesos
    tag_group: dev_mesos_agent
    tag_name: dev_mesos_agent1
    availability_zone: us-west-2a  # need one node in each zone

  dev_mesos_agent2:
    <<: *MesosAgentDefaults
    tag_name: dev_mesos_agent2
    availability_zone: us-west-2b  # need one node in each zone

  dev_mesos_agent3:
    <<: *MesosAgentDefaults
    tag_name: dev_mesos_agent3
    availability_zone: us-west-2c  # need one node in each zone
