# These settings are merged into config/settings.yml

aws:

  instance_default_prod: &ProdDefault
    region: us-west-2
    image_id: ami-6e1a0117  # Ubuntu
    min_count: 1
    max_count: 1
    instance_type: c4.2xlarge
    availability_zone: us-west-2a
    tag_name: prod_default
    tag_group: prod_nodes
    tag_manager: dlweber
    tag_service:
    tag_stage: production

  # ---
  # Zookeeper Nodes
  # - note definition and use of defaults: ZookeeperDefaults
  # - it's important that each instance has 'zookeeper' in the key and tag_name (case sensitive)

  prod_zookeeper1: &ZookeeperDefaults
    <<: *ProdDefault
    instance_type: t2.medium
    tag_service: zookeeper
    tag_group: prod_zookeeper
    tag_name: prod_zookeeper1
    availability_zone: us-west-2a  # need one node in each zone

  prod_zookeeper2:
    <<: *ZookeeperDefaults
    tag_name: prod_zookeeper2
    availability_zone: us-west-2b  # need one node in each zone

  prod_zookeeper3:
    <<: *ZookeeperDefaults
    tag_name: prod_zookeeper3
    availability_zone: us-west-2c  # need one node in each zone

  # ---
  # Mesos Nodes
  # - note definition and use of defaults: MesosMasterDefaults, MesosAgentDefaults
  # - it's important that each instance has 'mesos' in the key and tag_name (case sensitive)

  prod_mesos_master1: &MesosMasterDefaults
    <<: *ProdDefault
    tag_service: mesos
    tag_group: prod_mesos_master
    tag_name: prod_mesos_master1
    availability_zone: us-west-2a  # need one node in each zone

  prod_mesos_master2:
    <<: *MesosMasterDefaults
    tag_name: prod_mesos_master2
    availability_zone: us-west-2b  # need one node in each zone

  prod_mesos_master3:
    <<: *MesosMasterDefaults
    tag_name: prod_mesos_master3
    availability_zone: us-west-2c  # need one node in each zone

  prod_mesos_agent1: &MesosAgentDefaults
    <<: *ProdDefault
    instance_type: c4.4xlarge
    tag_service: mesos
    tag_group: prod_mesos_agent
    tag_name: prod_mesos_agent1
    availability_zone: us-west-2a  # need one node in each zone

  prod_mesos_agent2:
    <<: *MesosAgentDefaults
    tag_name: prod_mesos_agent2
    availability_zone: us-west-2b  # need one node in each zone

  prod_mesos_agent3:
    <<: *MesosAgentDefaults
    tag_name: prod_mesos_agent3
    availability_zone: us-west-2c  # need one node in each zone

  # Add more agents and/or modify code to auto-name instances and
  # just specify the number of instances to spin up (min_count, max_count).
